'use strict';

module.exports = {
    schiaffi: [
        'ha tirato uno schiaffo che ha fatto resettare il router. 💥',
        'ha mollato un ceffone così forte che gli antenati hanno chiesto scusa. 🖐️',
        'ha colpito con la forza di mille nonne arrabbiate. 👵💢',
        'ha stampato le cinque dita in faccia stile Wi-Fi. 📶',
        'ha dato una sberla che ha piegato lo spaziotempo. 🌌',
        'ha colpito così forte da far scordare la password del telefono. 📱',
        'ha tirato uno schiaffo termico: CPU in thermal throttling. 🌡️',
        'ha dato un ceffone fulmineo oltre i 360 Hz. 🖥️',
    ],
    insulti: [
        'Sei il motivo per cui gli alieni passano oltre senza fermarsi. 👽',
        'Sei utile quanto un semaforo in GTA. 🚦',
        'Il tuo albero genealogico dev’essere un cerchio perfetto. 🌳',
        'Se avessi un euro per ogni idea intelligente, sarei in debito. 💸',
        'Anche un file .txt vuoto ha più contenuti di te. 📄',
        'Hai due neuroni e stanno litigando per l’affidamento del terzo. 🧠',
        'Sei l’errore 404 dell’intelligenza umana. 🚫',
        'Il tuo QI potrebbe andare in underflow. 🔢',
    ],
    tette: [
        '🍒 Taglia: piattaforma d’atterraggio per zanzare. Voto: 2/10',
        '🍒 Taglia: due airbag esplosi. Voto: 8/10',
        '🍒 Taglia: meloni di stagione! Voto: 9/10',
        '🍒 Taglia: limoni acerbi. C’è potenziale. Voto: 5/10',
        '🍒 Taglia: palloncini gonfiati a elio. Voto: 8/10',
        '🍒 Taglia: versione overclockata di serie. Voto: 9/10',
    ],
    bacia: [
        'ha stampato un bacio appassionato a',
        'ha dato un bacino timido a',
        'ha lasciato un segno di rossetto sulla guancia di',
        'ha dato un bacio romantico sotto la pioggia a',
        'ha baciato con la precisione di un laser a',
        'ha stampato un bacio crittografato end-to-end sulla guancia di',
    ],
    scopa: [
        'ha acceso le vibes con',
        'ha creato una scena da telenovela con',
        'ha fatto salire troppo la temperatura della chat con',
        'ha fatto perdere la calma, ma con stile, a',
        'ha portato la chat in modalità troppo entusiasmo con',
        'ha chiuso la scena con un sorriso malizioso verso',
    ],
    paccasulculo: [
        'ha dato una pacca premium, con effetto sonoro incluso 🍑',
        'ha fatto una pacca da manuale, voto dieci e lode 🏆',
        'ha sferrato una pacca amichevole a velocità supersonica 💨',
        'ha lasciato una pacca firmata, timbrata e approvata ✅',
        'ha regalato una pacca di incoraggiamento, versione deluxe 🎁',
    ],
    uccidi: [
        'ha sconfitto in un duello immaginario',
        'ha battuto in una sfida a Mario Kart contro',
        'ha mandato KO a colpi di cuscino',
        'ha vinto una battaglia di meme contro',
        'ha fatto ragequitare per finta',
    ],
    abbraccia: [
        'ha stretto in un abbraccio da otto secondi esatti',
        'ha dato un abbraccio così caldo da sciogliere il ghiaccio',
        'ha avvolto in un abbraccio morbido come una coperta',
        'ha regalato un abbraccio con bonus serenità',
        'ha condiviso un abbraccio pieno di bene',
    ],
    sposa: [
        'ha tirato fuori un anello brillante e ha fatto la proposta a',
        'ha chiesto di sposarlo/a sotto una pioggia di coriandoli a',
        'ha preparato una proposta da film romantico per',
        'ha promesso pizza, serie TV e felicità a',
        'ha scelto il momento perfetto per fare la proposta a',
    ],
    fiori: [
        '🌷 un tulipano rosa e un sorriso grande così',
        '🌹 una rosa rossa con glitter immaginari',
        '🌻 un girasole con energia da giornata perfetta',
        '🌼 una margherita che sa di cose semplici e belle',
        '💐 un bouquet colorato che mette subito il buonumore',
        '🌸 un rametto fiorito e un abbraccio virtuale',
    ],
    verita: [
        'Qual è la figuraccia più grande che hai fatto in pubblico?',
        'Hai mai finto di stare male per evitare un impegno?',
        'Qual è l’ultima persona del gruppo che hai stalkerato sui social?',
        'Cosa pensi davvero del creatore del bot?',
        'Hai mai spiato il telefono di qualcuno di nascosto?',
    ],
    obbligo: [
        'Invia un audio in cui canti una sigla a squarciagola.',
        'Registra 30 secondi in cui fai il verso di una gallina disperata.',
        'Dichiara il tuo amore a caso a una persona del gruppo.',
        'Scrivi solo con emoji fino al tuo prossimo messaggio.',
        'Racconta una figuraccia vera senza fare nomi.',
    ],
};
